name: tig
version: git
summary: Text-mode interface for git
license: GPL-2.0-or-later
description: |
  Tig is an ncurses-based text-mode interface for Git. It functions mainly as a
  Git repository browser, but can also assist in staging changes for commit at
  chunk level and act as a pager for output from various Git commands.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

base: core18

plugs:
  config-tig:
    interface: personal-files
    read:
      - $HOME/.tigrc

apps:
  tig:
    command: bin/tig
    plugs:
      - config-tig

parts:
  tig:
    source: .
    plugin: autotools
    build-packages:
      - pkg-config
      - libncursesw5-dev
      - libreadline-dev
